stages: [deploy]

variables:
  CI_NODEJS_VERSION: 12-2020.11.30

deploy:
  interruptible: true
  stage: deploy
  image: ekino/ci-node:${CI_NODEJS_VERSION}
  tags: [docker, ek-docker, ekino, france]
  script:
    - npm config set user 0
    - npm config set unsafe-perm true
    - npm i -g vercel
    - vercel --name $VERCEL_PROJECT_NAME --confirm -t $VERCEL_TOKEN --prod
  only:
    - master
    - ci/deploy-from-gitlab
